testing

diff --git a/.github/workflows/deploy_release_to_dev.yml b/.github/workflows/deploy_release_to_dev.yml
--- a/.github/workflows/deploy_release_to_dev.yml
+++ b/.github/workflows/deploy_release_to_dev.yml
@@ -37,9 +37,10 @@ jobs:
         if: ${{ !startsWith(github.ref, 'refs/heads/release2/') }}
         steps:
             - run: |
-                echo "Validation failed: Workflow executed on non-release branch"
-                exit 1
-
+                if [[ {{ github.ref }} = refs/heads/release/* ]] 
+                then 
+                echo "Validation failed: Workflow executed on non-release branch" && exit 1 
+                fi
     show_push_vars:
         needs: validate_branch
         runs-on: ubuntu-latest
